version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - api
      - redis
    links:
      - api
      - redis
    env_file: .env
    environment:
      AUTH0_CALLBACK_URL: "http://localhost:3000/callback"
      EXPRESS_HOST: "0.0.0.0"
      API_URL: "http://api:8000"
      REDIS_HOST: "redis"
    volumes:
      - ./app:/home/cpanel/app
      - ./static:/home/cpanel/static
      - ./test:/home/cpanel/test
  api:
    image: "controlpanel:latest"
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    env_file: .env
    environment:
      ALLOWED_HOSTS: "*"
      DB_HOST: "db"
      DB_NAME: "controlpanel"
      DB_USER: "controlpanel"
      DEBUG: "True"
      PYTHONUNBUFFERED: 1
    volumes:
      - ~/.kube/config:/home/controlpanel/.kube/config
  db:
    image: "circleci/postgres:9.6.2"
    environment:
      POSTGRES_USER: "controlpanel"
      POSTGRES_DB: "controlpanel"
  migration:
    image: "controlpanel:latest"
    command: sh -c "until pg_isready -h db; do sleep 2; done; ./manage.py migrate"
    environment:
      DB_HOST: "db"
      DB_NAME: "controlpanel"
      DB_USER: "controlpanel"
    links:
      - db
    depends_on:
      - db
  redis:
    image: "redis:4.0.2-alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: ['redis-server', '--requirepass', '$REDIS_PASSWORD']
