version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - api
    links:
      - api
    env_file:
      - .env
    environment:
      AUTH0_CALLBACK_URL: "http://localhost:3000/callback"
      EXPRESS_HOST: "0.0.0.0"
      API_URL: "http://api:8000"
      NODE_RESTART: "1"
    volumes:
      - ./app:/home/cpanel/app
      - ./static:/home/cpanel/static
      - ./test:/home/cpanel/test
  api:
    image: "quay.io/mojanalytics/control-panel:api"
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=*
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DB_HOST=db
      - DB_NAME=controlpanel
      - DB_USER=controlpanel
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=control_panel_api.settings
  db:
    image: "circleci/postgres:9.6.2"
    environment:
      POSTGRES_USER: "controlpanel"
      POSTGRES_DB: "controlpanel"
