version: 2
jobs:

  build:

    docker:
      - image: circleci/node:7.9

    steps:
      - checkout

      - restore_cache:
          keys:
            - dep-cache-{{ checksum "package.json" }}
            - dep-cache-

      - run: npm install

      - save_cache:
          key: dep-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm test
