version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: yarn install
      - run: mkdir -p static/stylesheets
      - run: yarn run collect-static
      - run: yarn run test
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - static

  deploy:
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update && apk add --no-progress curl curl-dev
      - restore_cache:
          keys:
            - image-cache-{{ .Branch }}
            - image-cache-
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: image-cache-{{ .Branch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD} quay.io
            docker tag app "quay.io/mojanalytics/control-panel-frontend:${CIRCLE_SHA1}"
            docker tag app "quay.io/mojanalytics/control-panel-frontend:${CIRCLE_BRANCH}"
            docker push "quay.io/mojanalytics/control-panel-frontend:${CIRCLE_SHA1}"
            docker push "quay.io/mojanalytics/control-panel-frontend:${CIRCLE_BRANCH}"
      - deploy:
          name: Deploy to dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl ${JENKINS_URL}/job/control-panel/job/frontend/buildWithParameters \
                --data token=${JENKINS_JOB_TRIGGER_TOKEN} \
                --data COMMIT_HASH=${CIRCLE_SHA1} \
                --data BRANCH_NAME=${CIRCLE_BRANCH} \
                --user ${JENKINS_USER}:${JENKINS_TOKEN}
            fi

      - deploy:
          name: Deploy to alpha
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl ${ALPHA_JENKINS_URL}/job/control-panel/job/frontend/buildWithParameters \
                --data token=${JENKINS_JOB_TRIGGER_TOKEN} \
                --data COMMIT_HASH=${CIRCLE_SHA1} \
                --data BRANCH_NAME=${CIRCLE_BRANCH} \
                --user ${ALPHA_JENKINS_USER}:${ALPHA_JENKINS_TOKEN}
            fi

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
