version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - run: yarn install
      - run: mkdir -p static/stylesheets
      - run: yarn run collect-static
      - run: yarn run test
      - run: yarn run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - static

  docker_build_and_push:
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - restore_cache:
          keys:
            - image-cache-{{ .Branch }}
            - image-cache-
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: image-cache-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Push Docker image to Quay Container Registry
          environment:
            IMAGE: quay.io/mojanalytics/control-panel-frontend
          command: |
            docker login -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD} quay.io
            docker tag app "${IMAGE}:${CIRCLE_SHA1}"
            docker tag app "${IMAGE}:${CIRCLE_BRANCH}"
            docker push "${IMAGE}:${CIRCLE_SHA1}"
            echo "Pushed Docker image to ${IMAGE}:${CIRCLE_SHA1}"
            docker push "${IMAGE}:${CIRCLE_BRANCH}"
            echo "Pushed Docker image to ${IMAGE}:${CIRCLE_BRANCH}"

workflows:
  version: 2
  test-build-and-push-docker-image:
    jobs:
      - build_and_test
      - docker_build_and_push:
          requires:
            - build_and_test
