version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: yarn install
      - run: mkdir -p static/stylesheets
      - run: yarn run collect-static
      - run: yarn run test
      - run: yarn run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - static

workflows:
  version: 2
  test:
    jobs:
      - build_and_test
